services:
  ros2_camera:
    build:
      context: ./ros2_camera/
      dockerfile: Dockerfile.gpu
    container_name: ros2_camera
    environment:
      - ROS_DOMAIN_ID=9
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./ros2_camera/ros2_ws_src:/ros2_ws/src:ro
      - ./models:/data/models:ro
    command: ros2 launch perseption obstacle_detection.launch.py 
    devices:
      - /dev/video0:/dev/video0
    network_mode: host
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # Or specify a number e.g., 1, or specific IDs with device_ids: ['0', '1']
              capabilities: [gpu] # Request GPU capabilities

  ros2_rqt:
    build:
      context: ./ros2_rqt/
      dockerfile: Dockerfile
    container_name: ros2_rqt
    command: ros2 run rqt_image_view rqt_image_view
    devices:
    - /dev/dri:/dev/dri
    environment:
      - ROS_DOMAIN_ID=9
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1 
      - XDG_RUNTIME_DIR=/tmp/runtime-root
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    network_mode: host 
    ipc: host
